create database bank_management

CREATE TABLE customer_details(user_id INT GENERATED ALWAYS AS IDENTITY, 
							  user_pin INT, acc_number INT , 
							  acc_name varchar(50), 
							  acc_balance INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1), 
							  customer_contact BIGINT, customer_add varchar(100),
							  PRIMARY KEY(acc_number));
							  
CREATE TABLE employee_details(ep_id INT GENERATED ALWAYS AS IDENTITY, 
							  ep_password INT, ep_name varchar(50), 
							  ep_contact BIGINT, ep_address varchar(100),
							  PRIMARY KEY(ep_id));
							  
CREATE TABLE transaction_details(transaction_id INT GENERATED ALWAYS AS IDENTITY,
								 from_acc_number INT, to_acc_number INT, 
								 transfer_amount INT, transfer_date NOT NULL DEFAULT CURRENT_DATE,
								 PRIMARY KEY(transaction_id), 
								 FOREIGN KEY(from_acc_number) REFERENCES customer_details(acc_number),
								 FOREIGN KEY(to_acc_number) REFERENCES customer_details(acc_number));